import os

DEFAULT_QDRANT_URL = "http://localhost:6333"
DEFAULT_EMBEDDINGS_BASE_URL = "http://127.0.0.1:12346"
DEFAULT_EMBEDDING_MODEL = "v5-small-retrieval-Q8_0.gguf"

DEFAULT_COLLECTION_NAME = os.getenv("QDRANT_COLLECTION_NAME", "knowledgebase")
QDRANT_URL = os.getenv("QDRANT_URL", DEFAULT_QDRANT_URL)
EMBEDDINGS_BASE_URL = os.getenv(
    "LLAMAINDEX_EMBEDDINGS_BASE_URL",
    os.getenv("EMBEDDINGS_BASE_URL", DEFAULT_EMBEDDINGS_BASE_URL),
)
EMBEDDING_PROVIDER = os.getenv("LLAMAINDEX_EMBEDDING_PROVIDER", "llamafile")
EMBEDDING_MODEL = os.getenv("LLAMAINDEX_EMBEDDING_MODEL", DEFAULT_EMBEDDING_MODEL)
RETRIEVAL_TOP_K = int(os.getenv("RAG_RETRIEVAL_TOP_K", "2"))

LM_STUDIO_CHAT_BASE_URL = os.getenv("LM_STUDIO_CHAT_BASE_URL", "http://127.0.0.1:12345/v1")
LM_STUDIO_API_KEY = os.getenv("LM_STUDIO_API_KEY", "key")
CHAT_MODEL = os.getenv("LM_STUDIO_CHAT_MODEL", "gemma-4-12b")
